export type ConservationStatus = 'EX' | 'EW' | 'CR' | 'EN' | 'VU' | 'NT' | 'LC' | 'DD';
export type Kingdom = 'Animal' | 'Plant' | 'Fungi';

export interface Species {
  id: string;
  commonName: string;
  scientificName: string;
  kingdom: Kingdom;
  habitat: string;
  biome: string; // for terrarium background gradient
  conservationStatus: ConservationStatus;
  hints: [string, string, string, string, string]; // exactly 5 progressive hints
  imageUrl: string;
  charityUrl: string;
  charityName: string;
  climateImpact: string;
  funFact: string;
  emoji: string;
}

export const CONSERVATION_META: Record<ConservationStatus, { label: string; color: string; bg: string; description: string }> = {
  EX: { label: 'Extinct', color: '#6b7280', bg: 'rgba(107,114,128,0.15)', description: 'No longer exists anywhere on Earth.' },
  EW: { label: 'Extinct in the Wild', color: '#8b5cf6', bg: 'rgba(139,92,246,0.15)', description: 'Survives only in captivity.' },
  CR: { label: 'Critically Endangered', color: '#ef4444', bg: 'rgba(239,68,68,0.15)', description: 'Facing an extremely high risk of extinction.' },
  EN: { label: 'Endangered', color: '#f97316', bg: 'rgba(249,115,22,0.15)', description: 'Facing a very high risk of extinction.' },
  VU: { label: 'Vulnerable', color: '#eab308', bg: 'rgba(234,179,8,0.15)', description: 'Faces high risk if threats continue.' },
  NT: { label: 'Near Threatened', color: '#84cc16', bg: 'rgba(132,204,22,0.15)', description: 'Close to qualifying for a threatened category.' },
  LC: { label: 'Least Concern', color: '#10b981', bg: 'rgba(16,185,129,0.15)', description: 'Widespread and abundant.' },
  DD: { label: 'Data Deficient', color: '#a78bfa', bg: 'rgba(167,139,250,0.15)', description: 'Insufficient data to assess extinction risk.' },
};

export const SPECIES_DATABASE: Species[] = [
  // ─── ANIMALS ─────────────────────────────────────────────────────────
  {
    id: 'axolotl',
    commonName: 'Axolotl',
    scientificName: 'Ambystoma mexicanum',
    kingdom: 'Animal',
    habitat: 'Lake Xochimilco, Mexico City',
    biome: 'freshwater',
    conservationStatus: 'CR',
    hints: [
      "I inhabit a single lake complex in the world — a high-altitude freshwater basin that was once surrounded by the floating gardens of the Aztec empire. Fewer than 1,000 of my kind survive in the wild today.",
      "I possess one of the most remarkable superpowers in the animal kingdom: I can fully regenerate limbs, my spinal cord, my heart, and even portions of my brain. Scientists study me intensely for insights into human regenerative medicine.",
      "Unlike nearly all other amphibians, I never undergo metamorphosis. I retain my feathery external gills, my juvenile body shape, and my aquatic lifestyle my entire life — a biological phenomenon called neoteny.",
      "My grinning, wide-eyed face has made me one of the most beloved animals on the internet, and I am kept as a pet worldwide. Despite my popularity, my wild habitat continues to be destroyed by urban expansion and water pollution.",
      "I am also known as the 'Mexican Walking Fish,' though I am not a fish at all — I am a salamander. Aztec mythology believed I was the dog-like manifestation of the lightning god Xolotl, who transformed to avoid sacrifice.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ambystoma_mexicanum_%28axolotl%29.jpg/1200px-Ambystoma_mexicanum_%28axolotl%29.jpg',
    charityUrl: 'https://www.wwf.org.uk/',
    charityName: 'WWF — Freshwater Habitats',
    climateImpact: 'Rising temperatures in Mexico City intensify droughts that shrink the already fragile canal system of Xochimilco. Warmer water accelerates the growth of invasive water hyacinth, which depletes oxygen and suffocates the lake floor. Since 1998, the axolotl\'s wild population has collapsed by over 90%.',
    funFact: 'An axolotl can replace a lost limb in as little as 3 months — perfect down to the bone, muscle, and nerve cells.',
    emoji: '🦎',
  },
  {
    id: 'kakapo',
    commonName: 'Kākāpō',
    scientificName: 'Strigops habroptilus',
    kingdom: 'Animal',
    habitat: 'Offshore islands of New Zealand',
    biome: 'temperate_forest',
    conservationStatus: 'CR',
    hints: [
      "I am the world's heaviest parrot and the only flightless parrot alive. I am strictly nocturnal and hid so effectively from early explorers that they initially believed I was a myth.",
      "My feathers are moss-green and golden-yellow, giving me perfect camouflage in the fern-covered forests of the Southern Hemisphere. When threatened, I freeze completely still instead of fleeing.",
      "I can live for up to 90 years, making me one of the longest-lived birds ever recorded. I do not reach sexual maturity until I am nearly 10 years old, which makes recovery agonizingly slow.",
      "I breed only in years when the rimu tree produces heavy fruit — sometimes only once every 3 to 5 years. This rare, feast-driven breeding cycle has left my population devastatingly small.",
      "My total wild population has been counted: as of 2023, only 247 individuals exist. Each one has a name, a GPS tracker, and a dedicated human recovery team. Every single birth is livestreamed by the New Zealand government.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Kakapo_with_food_in_mouth.jpg/1200px-Kakapo_with_food_in_mouth.jpg',
    charityUrl: 'https://www.doc.govt.nz/our-work/kakapo-recovery/',
    charityName: 'DOC — Kākāpō Recovery Programme',
    climateImpact: 'Warming disrupts the mast-fruiting cycles of rimu trees, throwing off the breeding calendar the kākāpō has evolved over millions of years. Increased storm intensity also poses direct danger to the island sanctuaries these birds now call home.',
    funFact: 'The kākāpō\'s mating call can be heard over 5 km away. Males spend months inflating air sacs in their chests to produce it.',
    emoji: '🦜',
  },
  {
    id: 'saola',
    commonName: 'Saola',
    scientificName: 'Pseudoryx nghetinhensis',
    kingdom: 'Animal',
    habitat: 'Annamite Mountains, Vietnam & Laos',
    biome: 'tropical_forest',
    conservationStatus: 'CR',
    hints: [
      "I am one of the rarest large mammals on Earth. So few people have seen me alive that scientists call me the 'Asian Unicorn.' I was only discovered by Western science in 1992 — one of the largest zoological discoveries of the 20th century.",
      "I live in the dense, misty montane forests straddling the border of Vietnam and Laos, an area so remote it was largely uncharted before my discovery. My population is estimated at fewer than a few hundred individuals.",
      "I have long, parallel horns that can reach 50 cm and large scent glands below my eyes that I use to mark territory. I look like a cross between a large antelope and an oryx — but I am not closely related to either.",
      "No scientist has ever observed me in my natural habitat. Everything we know about my behavior comes from camera traps and a small number of individuals briefly kept by local villagers.",
      "I am a bovid — the same zoological family as cattle, bison, and buffalo. But I am so genetically distinct that I represent my own genus, Pseudoryx, with no close living relatives.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Saola_DWQ_00001.jpg/800px-Saola_DWQ_00001.jpg',
    charityUrl: 'https://www.savethesaola.org/',
    charityName: 'Saola Foundation',
    climateImpact: 'Habitat fragmentation caused by logging roads, combined with increasingly erratic rainfall from climate change, is shrinking the Annamite forest corridor the saola relies on. Snaring — still the primary threat — may intensify as impoverished local communities face food insecurity driven by climate disruption.',
    funFact: 'The saola was discovered when a joint survey team found a skull with unusual horns in a hunter\'s home in 1992. It took nearly a decade before one was ever photographed alive.',
    emoji: '🦌',
  },
  {
    id: 'snow-leopard',
    commonName: 'Snow Leopard',
    scientificName: 'Panthera uncia',
    kingdom: 'Animal',
    habitat: 'Hindu Kush & Himalayas, Central Asia',
    biome: 'alpine',
    conservationStatus: 'VU',
    hints: [
      "I inhabit some of the most extreme terrain on Earth — rocky slopes and glacial fields at altitudes above 3,000 metres. I have been called a 'ghost' because I am rarely seen, even by the researchers who dedicate their careers to finding me.",
      "My thick, smoke-grey coat is patterned with dark rosettes that provide near-perfect camouflage against the slate and snow of mountain cliffs. My wide, padded paws act like natural snowshoes on steep terrain.",
      "My tail is extraordinarily long — nearly as long as my body — and packed with fat for energy reserves. I wrap it around myself like a blanket in subzero temperatures.",
      "Unlike my big-cat cousins the lion and tiger, I cannot roar. Instead I communicate through chuffs, hisses, and a haunting, long-range wail called a pru. I am perfectly adapted to solitude.",
      "I am one of the top predators of the Himalayan ecosystem, primarily hunting blue sheep and ibex. My presence is so vital that communities in Nepal and India are paid conservation bonuses when a livestock kill is confirmed to be my work.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/SnowLeopard_4.jpg/1200px-SnowLeopard_4.jpg',
    charityUrl: 'https://snowleopard.org/',
    charityName: 'Snow Leopard Trust',
    climateImpact: 'The Himalayas are warming at twice the global average rate. As the treeline rises, prey and livestock push higher up mountains, forcing snow leopards into ever-shrinking ranges. Simultaneously, melting glaciers imperil the freshwater systems that entire mountain communities — and the leopards — depend on.',
    funFact: 'A snow leopard can leap up to 14 metres horizontally and 3 metres vertically — the equivalent of jumping over a double-decker bus from a standstill.',
    emoji: '🐆',
  },
  {
    id: 'pangolin',
    commonName: 'Ground Pangolin',
    scientificName: 'Smutsia temminckii',
    kingdom: 'Animal',
    habitat: 'Sub-Saharan Africa',
    biome: 'savanna',
    conservationStatus: 'VU',
    hints: [
      "I am the world's most heavily trafficked wild mammal, yet most people have never heard of me. My scales, made entirely of keratin — the same material as human fingernails — are believed by some cultures to have medicinal powers they do not actually possess.",
      "When threatened, I curl into a perfect ball, covering my soft underbelly with overlapping armour. My scales can withstand a lion's claws. I am, essentially, a living artichoke.",
      "I have no teeth. My tongue can be longer than my entire body, and I use it to extract termites and ants from underground colonies. My powerful claws can rip open concrete-hard termite mounds.",
      "I am the only mammal in the world that is fully covered in scales. My closest relatives are not armadillos or anteaters, despite the resemblance — those are convergent evolution. My nearest living cousins are actually carnivores like cats and dogs.",
      "All eight species of pangolin are threatened with extinction. Over one million pangolins were seized from illegal traders between 2000 and 2013 alone. I am a mammal, yet I am entirely silent — I have no vocal cords.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Pangolin_in_Kruger.jpg/1200px-Pangolin_in_Kruger.jpg',
    charityUrl: 'https://www.savepangolins.org/',
    charityName: 'Save Pangolins',
    climateImpact: 'Drought driven by climate change in southern Africa reduces termite and ant populations — the pangolin\'s sole food source — pushing pangolins into human settlements where they are more easily poached. Habitat loss for agricultural expansion under warming conditions further reduces their already fragmented range.',
    funFact: 'A pangolin\'s tongue is anchored not in its mouth, but in its pelvis. It retracts into its chest when not in use.',
    emoji: '🦔',
  },
  {
    id: 'blue-footed-booby',
    commonName: 'Blue-footed Booby',
    scientificName: 'Sula nebouxii',
    kingdom: 'Animal',
    habitat: 'Pacific Coast, Galápagos Islands',
    biome: 'marine',
    conservationStatus: 'LC',
    hints: [
      "I am one of the most recognisable seabirds in the world, instantly identified by a feature that is entirely unique to my species. That feature is the central theme of my elaborate mating ritual.",
      "I dive from heights of up to 30 metres into the ocean at over 100 km/h, folding my wings into a dart shape at the last second. Specialised air sacs in my skull protect my brain from the impact.",
      "My most striking feature is the result of diet: carotenoid pigments from fresh fish are processed into a distinctive colour. Males with the brightest version of this feature are the most attractive to females.",
      "I perform an elaborate mating dance called a 'sky-pointing' display: I raise my beak skyward, spread my wings, and shuffle my most famous assets directly in front of a potential mate.",
      "I am the Blue-footed Booby — and yes, my feet are genuinely, vividly blue. Males with brighter feet father healthier chicks. The word 'booby' comes from the Spanish bobo, meaning 'fool,' because early sailors could walk right up to me without me flying away.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Blue-footed-booby.jpg/1200px-Blue-footed-booby.jpg',
    charityUrl: 'https://galapagosconservancy.org/',
    charityName: 'Galápagos Conservation Trust',
    climateImpact: 'El Niño events, intensified by climate change, warm Pacific waters and reduce the sardine populations I depend on. Galápagos populations declined by 50% during 1997–98\'s El Niño. As oceans warm permanently, these crashes become more frequent.',
    funFact: 'The female blue-footed booby measures the blueness of a male\'s feet and will abandon a partner whose feet fade — a sign of declining health or poor diet.',
    emoji: '🐦',
  },
  {
    id: 'narwhal',
    commonName: 'Narwhal',
    scientificName: 'Monodon monoceros',
    kingdom: 'Animal',
    habitat: 'Arctic Ocean',
    biome: 'arctic',
    conservationStatus: 'LC',
    hints: [
      "I am a medium-sized whale found only in the frigid waters of the Arctic Ocean. For centuries, Europeans believed I did not truly exist — my most famous feature was sold by merchants as the horn of a mythical creature, worth ten times its weight in gold.",
      "I can dive to depths of over 1,500 metres, where I hunt Arctic cod and halibut in near-total darkness. My echolocation is so precise I can navigate through sea ice in the pitch-black polar winter.",
      "My most famous feature — a long, spiralling, ivory lance — is actually a tooth. It grows directly through the upper lip of the male and can reach 3 metres in length. It erupts with over 10 million nerve endings and is considered one of the most complex structures in the animal kingdom.",
      "My 'horn' was the subject of one of history's greatest hoaxes: medieval traders sold them as 'alicorn' — unicorn horns — to European royalty. Queen Elizabeth I paid the equivalent of £2.5 million for a single one.",
      "I am the Narwhal, the legendary 'unicorn of the sea.' My scientific name, Monodon monoceros, means 'one tooth, one horn' in Greek. My tusk is used for sensing the environment and, likely, for competing with other males.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Narwal2.jpg',
    charityUrl: 'https://www.worldwildlife.org/species/narwhal',
    charityName: 'WWF — Arctic Ocean',
    climateImpact: 'The Arctic is warming four times faster than the global average. Loss of sea ice destroys the pack-ice overwintering grounds narwhals use for shelter. As foreign shipping routes open through the Arctic, noise pollution disrupts the narwhal\'s echolocation. Increased killer whale presence in newly ice-free waters introduces a predator narwhals have never evolved defenses against.',
    funFact: 'Scientists discovered in 2017 that narwhal tusks can sense temperature, salinity, and pressure changes — making the horn a highly sensitive environmental instrument.',
    emoji: '🦄',
  },
  {
    id: 'okapi',
    commonName: 'Okapi',
    scientificName: 'Okapia johnstoni',
    kingdom: 'Animal',
    habitat: 'Congo Rainforest, Democratic Republic of Congo',
    biome: 'tropical_forest',
    conservationStatus: 'EN',
    hints: [
      "I was unknown to Western science until 1901, despite being the size of a horse. African explorer Sir Harry Johnston sent a skin back to London and caused a sensation — people thought he had discovered a new species of zebra.",
      "I have the tongue of a giraffe — literally: deep blue-black, prehensile, and long enough to wash my own eyelids. My tongue is a key tool for pulling leaves from dense forest understory.",
      "My legs are striped like a zebra's, but my body is a deep chestnut-brown. This pattern is thought to help young calves follow their mother through the dark forest. My stripes fade as I mature.",
      "I am the only living relative of the giraffe — we share a last common ancestor from around 11.5 million years ago. Despite my striped legs, I am not related to zebras at all.",
      "I am the Okapi, the 'forest giraffe' of the Congo. I was so elusive that the pygmy peoples of the Congo refused to tell European explorers about me for decades. I can only survive in undisturbed primary rainforest.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Okapi2.jpg/1200px-Okapi2.jpg',
    charityUrl: 'https://www.okapiconservation.org/',
    charityName: 'Okapi Conservation Project',
    climateImpact: 'The Congo Rainforest — the second largest on Earth — is under accelerating pressure from logging driven partly by economic instability linked to climate impacts. Shifting rainfall patterns disrupt the fruiting and leafing cycles the okapi depends on. Only 15,000–20,000 individuals are estimated to survive in the wild.',
    funFact: 'The okapi has scent glands on its feet that leave a tarry residue as it walks — it literally marks its territory with every step.',
    emoji: '🦓',
  },
  {
    id: 'mantis-shrimp',
    commonName: 'Peacock Mantis Shrimp',
    scientificName: 'Odontodactylus scyllarus',
    kingdom: 'Animal',
    habitat: 'Indo-Pacific coral reefs',
    biome: 'coral_reef',
    conservationStatus: 'LC',
    hints: [
      "I am one of the most violent predators in the ocean relative to my size. My strike is so fast and powerful that it creates collapsing cavitation bubbles that generate a flash of light, a shockwave, and a temperature briefly approaching the surface of the sun.",
      "I can punch with the force of a .22 calibre bullet. I have broken aquarium glass with a single strike. Scientists who study me in labs routinely use Kevlar gloves.",
      "My eyes contain 16 types of photoreceptors — compared to just 3 in humans. I can see ultraviolet, infrared, and circular polarised light simultaneously. My vision is so complex that scientists still do not fully understand how my brain processes it.",
      "Despite my devastating punch, I am also strikingly beautiful — my exoskeleton is a mosaic of electric blues, emerald greens, and fiery reds. Divers travel specifically to spot me on Indo-Pacific reefs.",
      "I am the Peacock Mantis Shrimp, also called the 'thumb splitter' by divers for obvious reasons. Despite the name, I am neither a mantis nor a shrimp — I am a stomatopod, belonging to an entirely separate crustacean lineage that split from shrimp 400 million years ago.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Odontodactylus_scyllarus.jpg/1200px-Odontodactylus_scyllarus.jpg',
    charityUrl: 'https://www.coralrestoration.org/',
    charityName: 'Coral Restoration Foundation',
    climateImpact: 'Ocean acidification and bleaching events are destroying the coral reef ecosystems the mantis shrimp uses for shelter and hunting. The Great Barrier Reef has lost 50% of its coral since 1995. As these habitats collapse, the rich biodiversity they support — including the mantis shrimp — faces an uncertain future.',
    funFact: 'The mantis shrimp\'s punching appendage, called a dactyl club, is one of the toughest biological materials ever studied — its spiral geometry is now being engineered into aerospace and military helmets.',
    emoji: '🦐',
  },
  {
    id: 'glass-frog',
    commonName: 'Glass Frog',
    scientificName: 'Hyalinobatrachium fleischmanni',
    kingdom: 'Animal',
    habitat: 'Central and South American rainforests',
    biome: 'tropical_forest',
    conservationStatus: 'LC',
    hints: [
      "I live in the rainforests of Central and South America, always near fast-moving streams. I am tiny — most species only reach 2–3 cm — and breathe partly through my skin.",
      "My skin is yellow-green and spotted, providing camouflage on the leaf surfaces where I rest during the day. But my most remarkable feature is not on my back — it's on my belly.",
      "When you look at my underside, you can see directly into my body. My organs — heart, liver, digestive tract — are fully visible through translucent tissue. I am, in a precise biological sense, transparent.",
      "I am a devoted father. Males guard clutches of eggs attached to leaves above streams for weeks, fighting off wasps and patting the eggs with water to keep them humid. When they hatch, the tadpoles drop directly into the water below.",
      "I am the Glass Frog. A 2022 study revealed a biological mystery: sleeping glass frogs reroute up to 89% of their red blood cells into their liver, making the rest of the body appear nearly invisible to predators — a previously unknown form of active camouflage.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Centrolenella_fleischmanni01.jpg/800px-Centrolenella_fleischmanni01.jpg',
    charityUrl: 'https://amphibianark.org/',
    charityName: 'Amphibian Ark',
    climateImpact: 'Glass frogs are canaries for rainforest health: they vanish immediately when stream water quality degrades. Increased drought frequency reduces the year-round stream flow they breed in. The chytrid fungus Batrachochytrium, supercharged by warming temperatures, has already driven 90 amphibian species to extinction.',
    funFact: 'Glass frogs sleep by making their blood cells virtually disappear. It\'s the only vertebrate known to use active transparency as a survival mechanism.',
    emoji: '🐸',
  },
  {
    id: 'dumbo-octopus',
    commonName: 'Dumbo Octopus',
    scientificName: 'Grimpoteuthis boylei',
    kingdom: 'Animal',
    habitat: 'Deep ocean, 3,000–7,000 m below surface',
    biome: 'deep_ocean',
    conservationStatus: 'DD',
    hints: [
      "I live in the hadal zones of the deep ocean — between 3,000 and 7,000 metres below the surface, where no sunlight has ever penetrated. I am one of the deepest-living octopus species known to science.",
      "I do not jet-propel through the water like my shallow-water cousins. I hover and drift through the crushing dark using two large fins that flap slowly on either side of my mantle, giving my silhouette an unmistakable, charming appearance.",
      "Because of the extreme pressure at my depth, I have no ink sac — there is nothing to hide from in the permanent dark. My suckers have no suckers in the traditional sense; instead I use papillae to locate microscopic organisms in the sediment.",
      "I am rarely observed alive. Most of what we know comes from remotely operated deep-sea vehicle footage. My eggs are large and yolk-rich, and the female can store sperm for months before depositing fully-developed eggs anywhere on the ocean floor.",
      "I am the Dumbo Octopus. My fins look like the ears of the Disney elephant Dumbo — hence the name. I am entirely harmless and have never been seen attacking anything larger than a small worm. Scientists estimate we may have dozens of undiscovered species in my genus.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Grimpoteuthis.jpg/800px-Grimpoteuthis.jpg',
    charityUrl: 'https://oceanfdn.org/',
    charityName: 'Ocean Foundation — Deep Sea Conservation',
    climateImpact: 'Deep-sea mining exploration — accelerating as surface mineral deposits are exhausted — threatens to destroy the sediment ecosystems the dumbo octopus inhabits. Ocean warming also alters circulation patterns that bring nutrient-rich water into the deep, potentially disrupting food chains we barely understand.',
    funFact: 'Dumbo octopuses have been recorded at 7,000 metres — deeper than Mount Everest is tall. They are the deepest-living octopuses ever observed.',
    emoji: '🐙',
  },

  // ─── PLANTS ──────────────────────────────────────────────────────────
  {
    id: 'victoria-amazonica',
    commonName: 'Giant Water Lily',
    scientificName: 'Victoria amazonica',
    kingdom: 'Plant',
    habitat: 'Amazon River basin, South America',
    biome: 'freshwater',
    conservationStatus: 'LC',
    hints: [
      "I am one of the largest flowering plants on Earth. My floating leaves can reach 3 metres in diameter, and my structural ribs are so strong that ancient engineers modelled Victorian-era iron bridges on my underside architecture.",
      "I bloom for only two nights. On the first night, my flower opens as a pure white, almost glowing bloom. It traps visiting beetles inside and coats them with pollen. On the second night, the flower turns pink and releases the beetles, which fly to another white bloom.",
      "My leaves have a waxy, water-repellent surface with upturned edges up to 10 cm tall. This creates a micro-environment on the leaf surface that retains warmth — which I use to generate heat and attract pollinators from kilometres away.",
      "Named after Queen Victoria and first described for Western science in 1836 from specimens found in Bolivia, I have become the national flower of Guyana. My pads are strong enough to support the weight of a child sitting still.",
      "I am the Victoria Amazonica, the Giant Water Lily of the Amazon. My blooms last only 48 hours. Their white-to-pink colour change is nature's signal to pollinators that pollen has been distributed and the flower is closing.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Victoria_Water-Lily_JBotGard_Berlin_edit02.jpg/1200px-Victoria_Water-Lily_JBotGard_Berlin_edit02.jpg',
    charityUrl: 'https://www.rainforest-alliance.org/',
    charityName: 'Rainforest Alliance',
    climateImpact: 'As Amazon droughts intensify — happening now every 5 years instead of every 50 — water levels in the floodplain lakes where giant water lilies grow drop critically during dry season. The 2023 Amazon drought was the worst recorded in 120 years.',
    funFact: 'Sir Joseph Paxton, who designed London\'s Crystal Palace for the 1851 Great Exhibition, drew direct inspiration from the structural ribs under a giant water lily leaf.',
    emoji: '🪷',
  },
  {
    id: 'rafflesia',
    commonName: 'Giant Rafflesia',
    scientificName: 'Rafflesia arnoldii',
    kingdom: 'Plant',
    habitat: 'Sumatra and Borneo, Southeast Asia',
    biome: 'tropical_forest',
    conservationStatus: 'EN',
    hints: [
      "I produce the largest individual flower on Earth — reaching up to 1 metre in diameter and weighing up to 11 kilograms. I have no leaves, no roots, and no stems. I am, biologically speaking, almost entirely a flower.",
      "I am a parasite. My entire body consists of thread-like filaments embedded inside the cells of my host vine, Tetrastigma. I am invisible for years at a time — the only evidence of my existence is a tiny brown bud that emerges after months of growth.",
      "To attract my pollinators — carrion flies — I emit a smell precisely mimicking rotting flesh. Visitors who find me in the jungle describe the odour as overwhelming from several metres away. My heat-generating tissues amplify the stench.",
      "I bloom for only 5 to 7 days before rapidly decomposing back into the forest floor. The probability of encountering me depends on finding a rare Tetrastigma vine, identifying the bud weeks in advance, and visiting within a 7-day window.",
      "I am Rafflesia arnoldii, named after Sir Stamford Raffles and Dr. Joseph Arnold who first described a specimen in 1818. Local people call me the 'corpse flower.' Despite the grandeur of my bloom, my seeds are tiny and sticky and can only be spread by tree shrews.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Rafflesia_magnifica.jpg/1200px-Rafflesia_magnifica.jpg',
    charityUrl: 'https://www.wwf.org.my/',
    charityName: 'WWF-Malaysia — Rainforest Protection',
    climateImpact: 'Logging and palm oil expansion eradicate entire populations of Tetrastigma vines — and with them, all the rafflesia buds embedded inside. Rafflesia cannot relocate or seed into disturbed ground. Once the host vine is cut, every rafflesia attached to it dies. Global warming amplifies deforestation pressures across Borneo.',
    funFact: 'Rafflesia has no chlorophyll, no photosynthesis, no vascular system. Genetically, some of its chromosomes are so thoroughly merged with its host vine\'s DNA that the species boundary is blurring.',
    emoji: '🌸',
  },
  {
    id: 'dragon-blood-tree',
    commonName: 'Dragon Blood Tree',
    scientificName: 'Dracaena cinnabari',
    kingdom: 'Plant',
    habitat: 'Socotra Island, Yemen',
    biome: 'dry_tropical',
    conservationStatus: 'VU',
    hints: [
      "I grow on a remote island in the Arabian Sea that has been called the 'Galápagos of the Indian Ocean' due to its extraordinary biodiversity — 37% of its plants exist nowhere else on Earth.",
      "My shape is unlike any other tree: my canopy is a perfect upturned umbrella of dense, interlocking branches, designed to funnel morning fog and mist down my trunk and into the dry soil below — a survival strategy for one of the most arid landscapes on Earth.",
      "My bark bleeds. When cut, I produce a deep crimson resin that has been used for centuries in violin varnish, ancient cave paintings, wound treatment, and even as a pigment for Roman-era lipstick.",
      "I can live for over 600 years. My umbrella-shaped canopy creates a microhabitat of shade beneath me where other plants and animals shelter, making me a keystone species of my entire island ecosystem.",
      "I am the Dragon Blood Tree of Socotra. My scarlet resin — called dragon's blood — was traded across the ancient world and appears in records from the ancient Assyrians, Greeks, and Romans. Climate change and overgrazing are now causing my population to crash.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Dragon_Blood_Trees_Socotra_Island.jpg/1200px-Dragon_Blood_Trees_Socotra_Island.jpg',
    charityUrl: 'https://www.wwf.org.uk/',
    charityName: 'WWF — Island Biodiversity',
    climateImpact: 'Socotra is experiencing more frequent and severe tropical cyclones due to warming Indian Ocean temperatures. Two back-to-back cyclones in 2015 flattened thousands of dragon blood trees. Simultaneously, the fog and mist precipitation the trees depend on is declining as regional climate patterns shift.',
    funFact: 'The dragon blood tree\'s crimson resin was so prized that Roman merchants established a dedicated "Dragon Blood Road" trade route from Socotra to the Mediterranean world.',
    emoji: '🌳',
  },
  {
    id: 'welwitschia',
    commonName: 'Welwitschia',
    scientificName: 'Welwitschia mirabilis',
    kingdom: 'Plant',
    habitat: 'Namib Desert, Namibia & Angola',
    biome: 'desert',
    conservationStatus: 'LC',
    hints: [
      "I am a living fossil. The oldest dated individuals are over 1,500 years old, and some may be 2,000 to 3,000 years old. I have remained essentially unchanged since the Jurassic period — my ancestors grew alongside dinosaurs.",
      "I grow in one of the driest places on Earth — the Namib coastal desert — where annual rainfall can be less than 25 mm. I survive almost entirely on coastal fog that rolls in from the Atlantic Ocean each morning.",
      "I produce exactly two leaves in my entire life. These leaves never fall and never stop growing — they split, fray, and curl over centuries into what looks like a heap of tattered plant debris. Botanists initially couldn't determine if I was a shrub, a cactus, or a fern.",
      "Charles Darwin, upon seeing a specimen, called me the 'platypus of the plant world.' My pollen fossils from 110 million years ago are identical to my living pollen — one of the longest confirmed stasis records in plant evolution.",
      "I am Welwitschia mirabilis — the 'miraculous' plant. My two leaves can reach 8 metres in length. I am so unusual that I form my own botanical order, division, and class — I am related to no other living plant species.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Welwitschia_mirabilis_Swakopmund.jpg/1200px-Welwitschia_mirabilis_Swakopmund.jpg',
    charityUrl: 'https://www.namibian.org/',
    charityName: 'Namibia Nature Foundation',
    climateImpact: 'Increasing temperatures in the Namib Desert are intensifying morning fog evaporation before welwitschia can absorb it. As the Benguela Current warms, the frequency of coastal fog roll-in is declining — directly reducing the primary water source for this ancient plant.',
    funFact: 'A welwitschia\'s leaves grow continuously from the base while the tips die — meaning parts of the leaf you can touch today began growing over a thousand years ago.',
    emoji: '🌿',
  },
  {
    id: 'corpse-flower',
    commonName: 'Titan Arum (Corpse Flower)',
    scientificName: 'Amorphophallus titanum',
    kingdom: 'Plant',
    habitat: 'Sumatra, Indonesia',
    biome: 'tropical_forest',
    conservationStatus: 'EN',
    hints: [
      "I produce the largest unbranched inflorescence of any plant on Earth — a single bloom structure that can reach 3 metres tall and weigh 70 kilograms. Thousands of tiny individual flowers are packed along a central spike called a spadix.",
      "I bloom only once every 7 to 10 years, and my bloom lasts only 24 to 48 hours before collapsing. When I do bloom, institutions that possess one become major news events — zoos and botanical gardens livestream my opening around the clock.",
      "I produce heat. During my brief window of bloom, my central spike reaches temperatures of up to 36°C — close to human body temperature. This heat volatilises my chemical cocktail and blasts my scent kilometres into the forest.",
      "Despite my popular name, I am not the same plant as Rafflesia. My odour is different: mine mimics a rotting corpse and rotting fish simultaneously. Entomologists have catalogued the specific compounds — dimethyl trisulfide, putrescine, and cadaverine.",
      "I am the Titan Arum — Amorphophallus titanum — known in Sumatra as 'bunga bangkai,' the corpse flower. My underground corm can weigh over 100 kg. Only about 1,000 individuals are thought to remain in the wild.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Amorphophallus_titanum_-_Steve_Cornish.jpg/800px-Amorphophallus_titanum_-_Steve_Cornish.jpg',
    charityUrl: 'https://www.rainforest-trust.org/',
    charityName: 'Rainforest Trust',
    climateImpact: 'The forests of Sumatra have lost more than 80% of their original cover in 50 years, primarily to palm oil plantations. The titan arum requires specific deep-shade rainforest conditions and cannot survive in degraded scrub. As Sumatra continues to warm, drought stress reduces the viability of remaining populations.',
    funFact: 'The smell of the titan arum in full bloom has been described as "a garbage truck parked inside a fish market on a hot summer day." It can be detected from over a kilometre away.',
    emoji: '🌺',
  },
  {
    id: 'ghost-orchid',
    commonName: 'Ghost Orchid',
    scientificName: 'Epipogium aphyllum',
    kingdom: 'Plant',
    habitat: 'Deep shade forests of Europe and Asia',
    biome: 'temperate_forest',
    conservationStatus: 'EN',
    hints: [
      "I am one of the rarest plants in Europe. There are long-term records of me appearing in a single English woodland only nine times in the past century. I have driven orchid hunters to obsession — and been declared extinct multiple times, only to reappear.",
      "I have no leaves. I contain no chlorophyll and have no capacity for photosynthesis. I am entirely dependent on a subterranean relationship with a soil fungus, from which I steal carbohydrates.",
      "Because I need no light, I spend most of my existence as an underground mat of coral-like roots, completely invisible. I only emerge above ground to flower — and only when conditions are perfectly right, which may be decades apart.",
      "My flower is a pale, waxy cream, occasionally flushed with pink, with a small lip that points upward — the inverse of most orchids. Up to four blooms open per stem, and they smell faintly of vanilla.",
      "I am the Ghost Orchid, Epipogium aphyllum. The name is doubly fitting: I appear ghostly white, and I haunt woodlands only fleetingly. A 1986 sighting in England was a national botanical event. I have no roots in the conventional sense — only fungal thread networks reaching deep into the soil.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Epipogium_aphyllum_Nizhny_Novgorod_%281%29.jpg/800px-Epipogium_aphyllum_Nizhny_Novgorod_%281%29.jpg',
    charityUrl: 'https://www.orchid-sg.com/',
    charityName: 'Orchid Specialist Group — IUCN',
    climateImpact: 'Ghost orchids depend on ancient, undisturbed woodland with a very specific soil fungal community. Forest fragmentation, changes in woodland management, and shifts in soil moisture from irregular rainfall are all disrupting the delicate mycorrhizal networks the ghost orchid relies on.',
    funFact: 'Ghost orchids were declared extinct in the United Kingdom in 1987. They were rediscovered — alive and flowering — in 2009.',
    emoji: '👻',
  },

  // ─── FUNGI ───────────────────────────────────────────────────────────
  {
    id: 'fly-agaric',
    commonName: 'Fly Agaric',
    scientificName: 'Amanita muscaria',
    kingdom: 'Fungi',
    habitat: 'Northern forests of Europe, Asia, and North America',
    biome: 'temperate_forest',
    conservationStatus: 'LC',
    hints: [
      "I am arguably the most culturally iconic mushroom in history. Ancient Siberian shamans documented rituals centred on consuming my dried body. Scholars debate whether I inspired the biblical 'soma,' the Viking berserk cult, and even Father Christmas.",
      "My red cap is studded with white flakes — remnants of a universal veil that covered me as I emerged from the soil. Rain washes these flakes away progressively, removing the most obvious identifying feature over time.",
      "I am toxic but rarely fatal to humans. The primary compound I contain is ibotenic acid and muscimol — psychoactive substances, not the deadly amatoxins of my relatives, the death caps. Ancient Norse berserker warriors may have consumed me before battle.",
      "I form an exclusive mycorrhizal partnership with specific trees — birch, pine, and spruce — and cannot grow without them. I am not a parasite: I trade water and minerals for the tree's sugars in an underground web of cooperation.",
      "I am the Fly Agaric, Amanita muscaria — the red-and-white toadstool of fairy tales, garden ornaments, and video games. My name comes from an ancient practice of placing my cap in milk to stupefy flies. I inspired the mushroom in Alice in Wonderland and virtually every fantasy world.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Amanita_muscaria_3_vliegenzwammetjes_op_rij.jpg/1200px-Amanita_muscaria_3_vliegenzwammetjes_op_rij.jpg',
    charityUrl: 'https://www.fungi.com/pages/fungi-perfecti-conservation',
    charityName: 'Fungi Perfecti — Mycelium Conservation',
    climateImpact: 'The fly agaric requires specific forest partnerships with birch and pine trees. As climate zones shift northward, the boreal forest ecosystems these trees depend on are fragmenting. Early spring warm spells trigger premature fruiting followed by killing frosts — reducing successful reproduction.',
    funFact: 'Reindeer actively seek out and eat fly agaric mushrooms in Lapland. Siberian shamans reportedly drank reindeer urine after the animals consumed the fungus, as the liver filters out the toxic compounds while retaining the psychoactive ones.',
    emoji: '🍄',
  },
  {
    id: 'zombie-fungus',
    commonName: 'Zombie-ant Fungus',
    scientificName: 'Ophiocordyceps unilateralis',
    kingdom: 'Fungi',
    habitat: 'Tropical rainforests of Thailand, Brazil, Ghana',
    biome: 'tropical_forest',
    conservationStatus: 'DD',
    hints: [
      "I am a parasite that takes complete control of my host's body. I do not merely infect — I rewire. My host continues to walk, climb, and grip — but none of these actions are its own decisions.",
      "My host is a specific species of carpenter ant. I infiltrate its body through its exoskeleton, colonise its muscle fibres with thread-like hyphae, and release chemicals that override its nervous system — but I never touch the brain itself.",
      "I compel my host to climb to a precise height — usually 25 cm above the forest floor — at high noon. The ant then clamps its mandibles into a specific vein on the underside of a leaf and dies, locked in place.",
      "From the dead ant's head, I erupt as a long stalk and release spores downward in a focused rain — directly onto the ant trail below, infecting the next generation. Each geographic population of mine is precisely tuned to its local ant species.",
      "I am Ophiocordyceps unilateralis — the inspiration for the fictional cordyceps infection in The Last of Us. In real life, I cannot infect mammals. But colonies of carpenter ants have evolved a collective intelligence: infected individuals are identified by smell and carried to 'graveyards' far from the nest.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Ophiocordyceps_unilateralis.png/800px-Ophiocordyceps_unilateralis.png',
    charityUrl: 'https://www.fungi.com/pages/fungi-perfecti-conservation',
    charityName: 'Fungi Perfecti — Conservation',
    climateImpact: 'As global warming pushes ecosystems into uncharted territory, precisely co-evolved host-parasite relationships like mine may unravel. The specific ant species I manipulate are themselves vulnerable to the same climate pressures reshaping tropical forests, potentially eliminating entire local zombie-ant ecosystems.',
    funFact: 'Carpenter ants perform a form of social immunity: healthy nest-mates detect infected individuals by chemical smell and carry them from the colony before the fungus can complete its life cycle.',
    emoji: '🧟',
  },
  {
    id: 'bleeding-tooth-fungus',
    commonName: 'Bleeding Tooth Fungus',
    scientificName: 'Hydnellum peckii',
    kingdom: 'Fungi',
    habitat: 'North American and European conifer forests',
    biome: 'temperate_forest',
    conservationStatus: 'LC',
    hints: [
      "When I am young and conditions are wet, I appear to weep. Small droplets of a deep crimson liquid bead across my white, porous surface — as if I am bleeding from thousands of tiny pores simultaneously.",
      "My crimson 'blood' is a concentrated pigment called atromentin, which my mycelium produces as a byproduct of mineral uptake. The drops are a form of guttation — pressure-exuded fluid — not analogous to blood in any biological sense.",
      "My flesh is white and spongy and tastes extremely bitter and astringent. I am not edible. However, atromentin — my red pigment — has been found in laboratory studies to have anticoagulant and antimicrobial properties.",
      "As I age, my white surface turns brown and tan, the droplets dry up, and any trace of my extraordinary appearance fades completely. Only the young, fresh specimens produce the startling crimson drops.",
      "I am Hydnellum peckii, the Bleeding Tooth Fungus, also called 'the Devil's Tooth.' Despite my dramatic appearance, I am entirely harmless. I partner with the roots of conifers in a mycorrhizal relationship, and am considered a bio-indicator of old-growth forest health.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Hydnellum_peckii1.jpg/1200px-Hydnellum_peckii1.jpg',
    charityUrl: 'https://www.northamericanmycologicalassociation.org/',
    charityName: 'North American Mycological Association',
    climateImpact: 'The bleeding tooth fungus is a bio-indicator for ancient, undisturbed conifer forest health. As old-growth forests across North America and Europe are logged or die back from heat stress and beetle infestations driven by warming winters, populations of rare mycorrhizal fungi like this one collapse.',
    funFact: 'The crimson pigment of the bleeding tooth fungus — atromentin — was studied by pharmaceutical researchers and found to inhibit the enzyme responsible for blood clotting in mammals. A living creature accidentally discoverd a natural anticoagulant.',
    emoji: '🩸',
  },

  // ─── MORE ANIMALS ────────────────────────────────────────────────────
  {
    id: 'aye-aye',
    commonName: 'Aye-aye',
    scientificName: 'Daubentonia madagascariensis',
    kingdom: 'Animal',
    habitat: 'Madagascar rainforests',
    biome: 'tropical_forest',
    conservationStatus: 'EN',
    hints: [
      "I am found only on a single island nation. Many local cultures consider me a death omen and would traditionally kill me on sight — a superstition that has contributed heavily to my dramatic population decline.",
      "I hunt for grubs inside tree bark using a unique method: I tap on the wood rapidly with my skeletal middle finger, listen for hollow resonances with bat-like ears, then gnaw through the bark with my constantly growing front teeth to extract the grub.",
      "My middle finger is skeletal and nearly twice the length of my other fingers — used exclusively as a probe. No other primate on Earth has evolved this hunting strategy. I fill the same ecological role as a woodpecker.",
      "I am the world's largest nocturnal primate. My coarse black fur, enormous reflective eyes, and rodent-like incisors made early naturalists argue for decades about whether I was a primate, a rodent, or something else entirely.",
      "I am the Aye-aye, Daubentonia madagascariensis — the sole surviving member of my entire family, Daubentoniidae. A second species of aye-aye once existed but went extinct, likely due to human persecution. My technique of tapping wood to find food is called percussive foraging.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Daubentonia_madagascariensis_2.jpg/800px-Daubentonia_madagascariensis_2.jpg',
    charityUrl: 'https://www.wwf.org.uk/',
    charityName: 'WWF — Madagascar',
    climateImpact: 'Madagascar is experiencing some of the worst deforestation on Earth, with slash-and-burn agriculture intensified by climate-driven crop failures. The aye-aye requires old-growth forest with large insect-filled trees. As forest fragments shrink, isolated populations face genetic collapse.',
    funFact: 'The aye-aye\'s percussive foraging evolved independently in exactly two other unrelated animals: the striped possum of Australia and the woodpecker — three completely separate lineages arriving at the same solution.',
    emoji: '🐒',
  },
  {
    id: 'platypus',
    commonName: 'Platypus',
    scientificName: 'Ornithorhynchus anatinus',
    kingdom: 'Animal',
    habitat: 'Eastern Australian rivers and streams',
    biome: 'freshwater',
    conservationStatus: 'NT',
    hints: [
      "When a specimen of me reached the British Museum in 1799, the curator George Shaw thought it was a taxidermist\'s hoax — a duck\'s bill sewn onto a beaver-like body. He reportedly took scissors to the pelt looking for stitches.",
      "I am one of only five surviving monotremes — the most ancient of all living mammal lineages. I lay leathery eggs like a reptile, yet nurse my young on milk like a mammal. I have no nipples; milk seeps through patches of my skin.",
      "My bill is packed with approximately 40,000 electroreceptors that detect the faint electric fields generated by the muscle contractions of my prey underwater. I hunt with my eyes, ears, and nostrils clamped shut — navigating entirely by electrical sense.",
      "Males possess venomous spurs on their hind legs — one of only a handful of venomous mammals. The venom causes excruciating, long-lasting pain that standard painkillers cannot relieve. It is not lethal to humans but can incapacitate a dog.",
      "I am the Platypus. In 2020 scientists discovered I glow blue-green under ultraviolet light — a property no one had looked for before. I am a mammal that lays eggs, senses electricity, carries venom, and is biofluorescent. Every time scientists study me, they discover a new impossibility.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Platypus_Photo.jpg/1200px-Platypus_Photo.jpg',
    charityUrl: 'https://www.australianwildlife.org/',
    charityName: 'Australian Wildlife Conservancy',
    climateImpact: 'The rivers the platypus depends on are being severely degraded by climate-driven drought and reduced rainfall. Multiple prolonged drought events in 2019–2020 — coinciding with Australia\'s catastrophic bushfires — collapsed local populations in key rivers. Modelling suggests 40% of habitat may be lost within 50 years.',
    funFact: 'Platypus electroreception is so precise that an individual can detect the electrical field of a single shrimp\'s heartbeat from 15 cm away, even in complete darkness and turbid water.',
    emoji: '🦆',
  },
  {
    id: 'goblin-shark',
    commonName: 'Goblin Shark',
    scientificName: 'Mitsukurina owstoni',
    kingdom: 'Animal',
    habitat: 'Continental slopes, 200–1,300 m depth, worldwide',
    biome: 'deep_ocean',
    conservationStatus: 'LC',
    hints: [
      "I am one of the rarest large fish ever photographed alive. My lineage dates back at least 125 million years to the Cretaceous period — I was patrolling the deep ocean when T. rex walked the Earth above me.",
      "My elongated, flattened snout is packed with electroreceptors that detect prey hiding in sediment. I do not need to see my food — I sense the electric field of its heartbeat in the absolute dark of the deep ocean.",
      "My jaws are arguably the most extreme in the animal kingdom: they are not fixed to my skull. When prey is detected, my entire jaw assembly projectiles forward out of my face like a spring-loaded trap, extending well beyond my snout tip.",
      "My skin is translucent pink because my blood vessels sit extremely close to the surface. In the total darkness of the deep, there is no predator to hide from and no camouflage needed — so I never evolved any.",
      "I am the Goblin Shark, Mitsukurina owstoni. Fewer than 50 individuals have ever been captured or observed. My extendable jaw — called slingshot feeding — can extend nearly 10% of my body length in under 0.3 seconds. I am so rarely encountered that each sighting makes international news.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Mitsukurina_owstoni_museum.jpg/1200px-Mitsukurina_owstoni_museum.jpg',
    charityUrl: 'https://www.sharktrust.org/',
    charityName: 'Shark Trust — Deep Sea',
    climateImpact: 'Deep-sea trawling, expanding as surface fisheries collapse due to warming, destroys the sediment ecosystems goblin sharks hunt in. Climate-driven changes to ocean circulation may also alter prey distribution in the deep-sea zones this ancient shark has fished for 125 million years.',
    funFact: 'If you scaled the goblin shark\'s jaw projection to a 6-foot human, it would be like having your lower jaw launch 7 inches out of your face — faster than you can blink.',
    emoji: '🦈',
  },
  {
    id: 'shoebill',
    commonName: 'Shoebill',
    scientificName: 'Balaeniceps rex',
    kingdom: 'Animal',
    habitat: 'Papyrus swamps of East and Central Africa',
    biome: 'freshwater',
    conservationStatus: 'VU',
    hints: [
      "I stand up to 1.4 metres tall and am one of the most unnervingly still large birds alive. I can remain motionless for up to 30 minutes waiting for prey to surface. Ornithologists describe watching me as like watching a prehistoric statue.",
      "My bill is one of the most formidable in the bird world — 20 cm long, 10 cm wide, and hooked like a billhook at the tip. I have been documented swallowing juvenile crocodiles whole. I can decapitate a lungfish with a single snap.",
      "I am known for a greeting behaviour called billing: I clap my massive bill rapidly, producing a loud machine-gun rattling sound while bowing my head. I do this primarily when a mate or offspring approaches after an absence.",
      "I fly with my neck retracted like a heron rather than outstretched like a stork. My wingspan can reach 2.4 metres, yet I rarely fly at all — I prefer to walk slowly and deliberately through papyrus swamps with my head angled down.",
      "I am the Shoebill, Balaeniceps rex — the 'whale-headed king.' Ancient Egyptians depicted me prominently in their swamp art. Fewer than 8,000 individuals survive today across the isolated papyrus swamps of Uganda, Sudan, and DR Congo.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Balaeniceps_rex_-Ueno_Zoo%2C_Tokyo%2C_Japan-8a.jpg/800px-Balaeniceps_rex_-Ueno_Zoo%2C_Tokyo%2C_Japan-8a.jpg',
    charityUrl: 'https://www.wcs.org/',
    charityName: 'Wildlife Conservation Society — Africa',
    climateImpact: 'Papyrus swamps — the shoebill\'s exclusive habitat — are being drained for agriculture at an accelerating rate as climate-linked water stress intensifies competition over land. Lake levels across East Africa have become increasingly volatile, flooding or desiccating the papyrus margins the shoebill breeds in.',
    funFact: 'Shoebills can stand so perfectly still for so long that hippos, otters, and monitor lizards routinely walk past them at close range without reacting — they simply cannot process the shoebill as a living thing.',
    emoji: '🦤',
  },
  {
    id: 'fossa',
    commonName: 'Fossa',
    scientificName: 'Cryptoprocta ferox',
    kingdom: 'Animal',
    habitat: 'Madagascar rainforests',
    biome: 'tropical_forest',
    conservationStatus: 'VU',
    hints: [
      "I am the apex predator of my island — an isolated landmass where I evolved in complete isolation from every other predator on Earth. I am the largest carnivore native to my island, and I can hunt prey up to my own bodyweight.",
      "I look like a cross between a cat and a mongoose, but I am neither. My closest relatives are a group of carnivores endemic to my island called euplerids — found nowhere else. My catlike body shape is a result of convergent evolution, not cat ancestry.",
      "I am an exceptional treetop hunter with semi-retractable claws and a tail as long as my body for balance. I am one of the only non-primate mammals that routinely hunts lemurs by chasing them through the forest canopy at full speed.",
      "I am unusual among carnivorans: young females temporarily develop male anatomical characteristics during adolescence — a phenomenon called transient masculinisation — thought to protect them from aggression by dominant males during their vulnerable development period.",
      "I am the Fossa, Cryptoprocta ferox — my name translates to 'hidden anus' in Latin, a reference to an unusual scent gland. Despite my fearsome reputation in Malagasy folklore, I typically avoid humans. Fewer than 2,500 adults are estimated to remain in the wild.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Cryptoprocta_ferox_-_Nahampoana.jpg/1200px-Cryptoprocta_ferox_-_Nahampoana.jpg',
    charityUrl: 'https://www.wwf.org.uk/',
    charityName: 'WWF — Madagascar Forest',
    climateImpact: 'Only about 10% of Madagascar\'s original forest survives. Climate-driven drought and intensifying cyclone damage is killing remaining forest patches. Without continuous forest, the fossa cannot hunt, breed, or disperse. As habitat fragments shrink below critical size, local populations become genetically isolated and collapse.',
    funFact: 'Despite looking like a cat in almost every way, the fossa cannot purr. Instead it communicates through a range of yowls, growls, and a haunting scream during mating season audible over a kilometre away.',
    emoji: '🐈',
  },
  {
    id: 'numbat',
    commonName: 'Numbat',
    scientificName: 'Myrmecobius fasciatus',
    kingdom: 'Animal',
    habitat: 'Wandoo eucalyptus woodland, Western Australia',
    biome: 'temperate_forest',
    conservationStatus: 'EN',
    hints: [
      "I am one of Australia\'s most visually striking marsupials — rust-red with distinctive white stripes across my back, a black eye-stripe, and a bushy tail I hold upright like a squirrel. Despite my vivid colouring, very few Australians have ever seen me in the wild.",
      "I am Australia\'s only fully diurnal marsupial. I am active only during daylight hours, because my food source is active only during the day. I eat one thing exclusively: termites. I consume up to 20,000 per day, which is my entire caloric requirement.",
      "My tongue is extraordinarily long and sticky — it can flick in and out 100 times per minute. Unlike anteaters, I do not dig into termite mounds; I access the shallow feeding galleries just a centimetre below the leaf litter surface.",
      "Unlike virtually all other marsupials, I have no brood pouch. My young are so tiny at birth (0.2 g) that they cling directly to my belly fur and are dragged along the ground as I forage. When they grow too large, I hide them in a hollow log.",
      "I am the Numbat, the banded anteater — Australia\'s faunal emblem of Western Australia. My total global population has collapsed to fewer than 1,000 individuals in just two or three tiny woodland patches. Introduced foxes and cats eliminated me from 99% of my former range.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Numbat.jpg/1200px-Numbat.jpg',
    charityUrl: 'https://www.wwf.org.au/',
    charityName: 'WWF-Australia — Numbat Recovery',
    climateImpact: 'The wandoo eucalyptus woodlands the numbat depends on are dying back from combined climate-driven drought and record-breaking heatwaves. The extreme heat events of 2019–2020 killed adult numbats directly from hyperthermia — a new and devastating extinction pressure on animals already hanging by a thread.',
    funFact: 'A numbat\'s tongue flicks at up to 100 times per minute yet has no muscle control whatsoever — it uses gravity and surface tension to collect termites, not active manipulation.',
    emoji: '🦡',
  },
  {
    id: 'hammerhead-shark',
    commonName: 'Scalloped Hammerhead Shark',
    scientificName: 'Sphyrna lewini',
    kingdom: 'Animal',
    habitat: 'Tropical and warm temperate oceans worldwide',
    biome: 'marine',
    conservationStatus: 'CR',
    hints: [
      "I am one of the ocean\'s most iconic predators, instantly recognisable by a head shape so unusual that biologists debated its exact purpose for over a century. I swim in schools of up to 500 individuals — one of the largest aggregations of any large shark species.",
      "My head houses the most sophisticated electrical sensory system of any shark. The lobes extending to either side contain hundreds of electroreceptors arranged in a broader arc than standard sharks — giving me near-panoramic electromagnetic scanning of the seafloor.",
      "My distinctive head shape also makes me one of the most agile sharks in the sea. By banking sharply, I use my broad cephalofoil as a hydrofoil to execute tight turns other sharks cannot achieve — a direct evolutionary trade-off between sensory power and manoeuvrability.",
      "I am viviparous — I give birth to live young connected to a yolk-sac placenta inside my womb, like a mammal. I can produce up to 31 pups in a single litter after a gestation period of 9 to 10 months.",
      "I am the Scalloped Hammerhead, Sphyrna lewini. My global population has declined by over 70% in 50 years due to shark finning — my fins are among the most valued in the shark fin trade. Atlantic populations have declined by 99%. I am now listed as Critically Endangered.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Sphyrna_lewini_head.jpg/800px-Sphyrna_lewini_head.jpg',
    charityUrl: 'https://sharkconservationfund.org/',
    charityName: 'Shark Conservation Fund',
    climateImpact: 'Ocean warming is shifting the thermal range of tuna and rays — the prey hammerheads track — pushing sharks into new areas with different fishing pressures. Coral reef degradation from bleaching is destroying critical nursery habitats where juvenile hammerheads shelter for their first years of life.',
    funFact: 'Scalloped hammerheads form precise social hierarchies within their massive schools: larger females always occupy the centre, with smaller individuals arranged in rings by size around them — as structured as any primate society.',
    emoji: '🦈',
  },
  {
    id: 'tardigrade',
    commonName: 'Tardigrade (Water Bear)',
    scientificName: 'Ramazzottius varieornatus',
    kingdom: 'Animal',
    habitat: 'Everywhere — mosses, glaciers, deep ocean, hot springs',
    biome: 'freshwater',
    conservationStatus: 'LC',
    hints: [
      "I am the most indestructible animal ever discovered by science. I can survive pressures six times greater than the deepest ocean trench, temperatures from near absolute zero to 150°C, and direct exposure to the vacuum of outer space for 10 days.",
      "I am microscopic — between 0.1 and 1.5 mm long. Despite my size, I have a brain, four pairs of stubby clawed legs, a muscular pharynx, and eyes. I have been found simultaneously in Antarctic glaciers, Himalayan hot springs, Amazon rainforest, and your garden moss.",
      "When conditions become extreme, I enter a state called cryptobiosis, drying into a barrel shape called a \'tun.\ In this state I have no measurable metabolism and can survive for decades. One specimen revived after 30 years of deep freezing.",
      "I was sent to the Moon aboard the Israeli Beresheet spacecraft, which crash-landed in 2019. Scientists calculated I likely survived the impact in cryptobiosis. There may be living tardigrades on the lunar surface right now.",
      "I am the Tardigrade, or Water Bear. I have survived all five of Earth\'s mass extinction events. My genome includes a protein called Dsup — Damage Suppressor — that physically wraps around my DNA to protect it from radiation. Scientists have since transferred this gene into human cells in the laboratory.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Scanning_Electron_Micrograph_of_Milnesium_tardigradum_in_active_state_-_journal.pone.0045682.g001-2.png/800px-Scanning_Electron_Micrograph_of_Milnesium_tardigradum_in_active_state_-_journal.pone.0045682.g001-2.png',
    charityUrl: 'https://www.gbif.org/',
    charityName: 'GBIF — Biodiversity Data',
    climateImpact: 'While tardigrades themselves are nearly indestructible, they are ecosystem engineers of moss and soil crust communities that are highly sensitive to climate. The moss habitats tardigrades inhabit are being destroyed by UV radiation in ozone-depleted areas and rapid desertification driven by drought.',
    funFact: 'A 2016 experiment found tardigrades exposed to radiation 1,000 times lethal to humans survived. The Dsup protein that protects their DNA has been successfully expressed in human cells in the lab — a step toward radiation-resistant human tissue.',
    emoji: '🐻',
  },

  // ─── MORE PLANTS ──────────────────────────────────────────────────────
  {
    id: 'venus-flytrap',
    commonName: 'Venus Flytrap',
    scientificName: 'Dionaea muscipula',
    kingdom: 'Plant',
    habitat: 'Coastal bogs of North and South Carolina, USA',
    biome: 'freshwater',
    conservationStatus: 'VU',
    hints: [
      "I am the most famous carnivorous plant in the world. I live in only one place on Earth — the nutrient-poor, acidic coastal bogs of a single US state — where I evolved animal-trapping as a strategy to obtain nitrogen the waterlogged soil cannot provide.",
      "My trap consists of two hinged lobes edged with interlocking teeth. The inside surface of each lobe contains three trigger hairs. An insect must touch at least two hairs, or the same hair twice within 20 seconds, before I snap shut — preventing false triggers from falling raindrops.",
      "Once closed, I take days or weeks to fully digest my prey. I secrete digestive enzymes directly onto the insect and absorb the dissolved nutrients through my leaf surface. After digestion, my trap reopens — sometimes still containing the hollow exoskeleton.",
      "Despite my fame, I grow in an area spanning only a 90-mile radius. Commercial poaching decimates wild populations — it is a felony in North Carolina to collect me without a permit, punishable by up to 25 years in prison for large-scale operations.",
      "I am the Venus Flytrap, Dionaea muscipula — the only member of my genus in the world. Charles Darwin called me \'one of the most wonderful plants in the world.\' I can snap shut in as little as 100 milliseconds — one of the fastest movements in the entire plant kingdom.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Venus_Flytrap_showing_trigger_hairs.jpg/1200px-Venus_Flytrap_showing_trigger_hairs.jpg',
    charityUrl: 'https://www.ncplantconservation.org/',
    charityName: 'NC Plant Conservation Program',
    climateImpact: 'Venus flytraps depend on periodic wildfire to maintain the open, boggy structure of longleaf pine savannas. Climate change intensifies droughts that make controlled burns dangerous and unpredictable, while more intense storms damage the sensitive bog hydrology the plant requires.',
    funFact: 'Venus flytraps can count. They require two separate trigger-hair touches before snapping, and if an insect continues stimulating the hairs after capture, the trap closes tighter and digestion begins faster — the plant is literally counting to accelerate feeding.',
    emoji: '🌱',
  },
  {
    id: 'baobab',
    commonName: "Giant Baobab",
    scientificName: 'Adansonia grandidieri',
    kingdom: 'Plant',
    habitat: 'Western Madagascar dry deciduous forest',
    biome: 'dry_tropical',
    conservationStatus: 'EN',
    hints: [
      "I have been called the \'tree of life\' and the \'upside-down tree\' — my bare winter branches look so much like roots that legend says God planted me upside-down as punishment. I can live for over 1,500 years.",
      "My trunk is not traditional wood — it is made of fibrous, spongy tissue capable of storing up to 120,000 litres of water. During droughts, elephants strip my bark with their tusks and tusks to drink the moisture held in my fibres.",
      "My bark is fireproof. My trunk survives grassland fires that kill all surrounding trees. Some individuals have hollow interiors that local communities have used as homes, prisons, chapels, and even pubs over the centuries.",
      "I bloom for only one night. My white flowers must be pollinated by fruit bats and hawk moths before dawn. If not pollinated, they fall. The timing of my single-night blooming is increasingly disrupted by warming temperatures shifting bat flight seasons.",
      "I am the Giant Baobab, Adansonia grandidieri — found only on Madagascar. Africa\'s largest baobab species has been dying rapidly: six specimens over 1,500 years old collapsed between 2005 and 2017. Scientists link this unprecedented die-off directly to warming temperatures and prolonged drought.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Madagascar_Morondava_Baobab_1025.jpg/800px-Madagascar_Morondava_Baobab_1025.jpg',
    charityUrl: 'https://www.bgci.org/',
    charityName: 'Botanical Gardens Conservation International',
    climateImpact: 'The nine oldest and largest baobab trees ever recorded — some over 2,500 years old — began partially or wholly collapsing between 2005 and 2017. A 2018 Nature Plants paper called it "unprecedented and shocking" and attributed the die-off to climate change. The trees had survived every prior human era intact.',
    funFact: 'Some African baobab trunks are large enough that entire ecosystems nest inside them — colonies of bats, owls, insects, lizards, and in several documented cases, continuous human habitation going back centuries.',
    emoji: '🌲',
  },
  {
    id: 'monkey-puzzle-tree',
    commonName: 'Monkey Puzzle Tree',
    scientificName: 'Araucaria araucana',
    kingdom: 'Plant',
    habitat: 'Andes mountains of Chile and Argentina',
    biome: 'alpine',
    conservationStatus: 'EN',
    hints: [
      "I am a living fossil — my lineage dates back 200 million years to the Triassic period. My distinctive silhouette, with spidery branches radiating from a tall straight trunk, has not changed significantly since dinosaurs walked beneath me.",
      "My leaves are thick, hard, triangular scales that completely encase each branch in overlapping armour. They are so sharply tipped and densely packed that no animal has ever been reliably documented climbing me. My popular name arose when an English visitor remarked that climbing me \'would puzzle a monkey.\'",
      "My seeds — large, edible nuts called piñones — were the staple food of the Pehuenche indigenous people of the Andes for thousands of years. Each cone contains up to 200 seeds and takes nearly three years to mature on the tree.",
      "I can live for over 1,000 years and reach 50 metres tall. I have separate male and female trees, and my massive cones — up to 18 cm across — fall explosively when mature with enough force to injure a person standing beneath me.",
      "I am the Monkey Puzzle Tree, Araucaria araucana — both the national tree of Chile and an endangered species. I exist only in a narrow Andean band. My seeds cannot disperse farther than they fall, so my range expands at geological pace. A single wildfire can eliminate a century of recovery.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Araucaria_araucana_forest.jpg/800px-Araucaria_araucana_forest.jpg',
    charityUrl: 'https://www.rainforest-trust.org/',
    charityName: 'Rainforest Trust — Andean Forests',
    climateImpact: 'Andean glaciers sustaining the moisture balance of monkey puzzle forests are retreating rapidly. Wildfire frequency in Chilean mountain forests is increasing with drought and warming — killing trees that survived for centuries. The species reproduces slowly; populations cannot recover at the pace fire now destroys them.',
    funFact: 'Monkey puzzle pollen has been found in Antarctic ice cores — these trees once grew on the Antarctic continent before it separated from South America 35 million years ago.',
    emoji: '🌴',
  },
  {
    id: 'rainbow-eucalyptus',
    commonName: 'Rainbow Eucalyptus',
    scientificName: 'Eucalyptus deglupta',
    kingdom: 'Plant',
    habitat: 'Tropical rainforests of the Philippines and nearby islands',
    biome: 'tropical_forest',
    conservationStatus: 'LC',
    hints: [
      "I am the only eucalyptus species native to the Northern Hemisphere. While nearly all eucalyptus trees are Australian, I evolved in isolation on volcanic Western Pacific islands, adapting to tropical monsoon conditions completely unlike the dry Australian climate.",
      "My bark peels away in irregular patches throughout the year, revealing vivid layers of fresh green underneath. As this new bark ages, it transitions through bright yellow, orange, red, purple, and finally blue-grey before peeling again — in a continuous, overlapping cycle.",
      "The result of my continuously peeling bark is a trunk simultaneously covered in every colour of the visible spectrum — shifting greens, blues, purples, oranges, and reds in a mosaic that changes every time you visit. I am frequently called the most visually spectacular tree in the world.",
      "I can grow at extraordinary speed — up to 3 metres per year under ideal conditions — and reach over 70 metres tall. My rapid growth is exploited commercially in pulp plantations across the Pacific, ironically making the most colourful tree in the world into white paper.",
      "I am the Rainbow Eucalyptus, Eucalyptus deglupta. My scientific name means \'fruit with many covers.\' While I am not currently threatened, tropical deforestation in the Philippines is eliminating ancient primary forest specimens that took decades to develop their full spectral depth of colour.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Eucalyptus_deglupta.jpg/800px-Eucalyptus_deglupta.jpg',
    charityUrl: 'https://www.rainforest-alliance.org/',
    charityName: 'Rainforest Alliance — Southeast Asia',
    climateImpact: 'Typhoons, intensified by warming Pacific Ocean temperatures, are increasingly toppling old-growth specimens that took decades to develop their full spectral display. The Mindanao island forests where the most spectacular wild populations grow have lost 80% of original forest cover since 1950.',
    funFact: 'The rainbow eucalyptus is the primary global source of white printing paper — the single most colourful tree in the world produces the paper people print on in black and white.',
    emoji: '🌈',
  },

  // ─── MORE FUNGI ───────────────────────────────────────────────────────
  {
    id: 'lions-mane',
    commonName: "Lion's Mane Mushroom",
    scientificName: 'Hericium erinaceus',
    kingdom: 'Fungi',
    habitat: 'Old-growth hardwood forests of North America, Europe, and Asia',
    biome: 'temperate_forest',
    conservationStatus: 'LC',
    hints: [
      "I grow on aging and dying hardwood trees and I look like nothing else in the fungal kingdom. My fruiting body hangs from a tree wound as a cascading waterfall of long, white, hair-like spines — giving me the appearance of a large white pom-pom or a frozen icicle sculpture.",
      "Unlike most mushrooms that release spores from gills or pores, I drop spores from the tips of thousands of pendant spines. These spines can reach 4 cm in length and turn slightly cream-yellow as I age and dry.",
      "I am edible and considered a culinary delicacy in Chinese and Japanese cuisine. My flesh is chewy and mild — frequently compared to crab or lobster in texture — making me one of the most prized medicinal and culinary fungi in the world.",
      "Research since the 1990s has identified compounds in my flesh — erinacines and hericenones — that cross the blood-brain barrier and stimulate the production of Nerve Growth Factor (NGF), which promotes the growth and protection of neurons.",
      "I am the Lion\'s Mane Mushroom, Hericium erinaceus. Clinical trials in Japan have shown consuming me significantly improves mild cognitive impairment markers in elderly patients. Traditional Chinese medicine documented my brain-supporting properties centuries ago. I am now among the most researched medicinal mushrooms globally.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/2013-11-08_Hericium_erinaceus_281616.jpg/1200px-2013-11-08_Hericium_erinaceus_281616.jpg',
    charityUrl: 'https://www.namyco.org/',
    charityName: 'North American Mycological Association',
    climateImpact: 'I depend on old-growth forests with large declining trees. As temperate forests are logged and heat-stressed trees die before reaching the large diameters I prefer as substrate, populations of this slow-colonising fungus decline. I am a bio-indicator of pristine, ancient woodland that has not been disturbed for generations.',
    funFact: 'Lion\'s mane extracts shown in laboratory studies to reverse beta-amyloid plaque destruction of neurons — the same plaques associated with Alzheimer\'s disease. Human trials investigating this effect are currently active in multiple countries.',
    emoji: '🦁',
  },
  {
    id: 'indigo-milk-cap',
    commonName: 'Indigo Milk Cap',
    scientificName: 'Lactarius indigo',
    kingdom: 'Fungi',
    habitat: 'Coniferous and deciduous forests of North America, East Asia, and Mexico',
    biome: 'temperate_forest',
    conservationStatus: 'LC',
    hints: [
      "I am among the most visually striking mushrooms in the world — and I achieve my remarkable appearance through an entirely internal mechanism. My entire fruiting body, from cap to gills to stem, is a vivid, deep indigo-blue.",
      "When I am cut or broken, I bleed. My latex — the equivalent of sap — is a vivid, electric indigo that oxidises in air and transitions from pure blue to grey-green within 30 minutes, staining knives, hands, and cutting boards distinctly blue.",
      "I am edible and widely eaten in Mexico, where I am called \'indigo de pino\' and appear regularly in markets. In East Asia I am considered a delicacy despite my alarming appearance. My taste is mild, slightly peppery, and distinctly mushroom-like.",
      "I form mycorrhizal partnerships with both coniferous and deciduous trees — exchanging minerals for sugars underground. I am one of the rare mycorrhizal fungi that partners successfully with multiple tree families, giving me one of the broadest forest ranges of any coloured mushroom.",
      "I am the Indigo Milk Cap, Lactarius indigo — one of the few naturally blue foods in the world. My pigment is a compound called azulene, which has been identified as a potential antifungal and natural food dye. Indigenous groups in Oaxaca, Mexico have harvested and eaten me for centuries.",
    ],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Lactarius_indigo_48568.jpg/1200px-Lactarius_indigo_48568.jpg',
    charityUrl: 'https://www.namyco.org/',
    charityName: 'North American Mycological Association',
    climateImpact: 'The mixed pine-oak forests the indigo milk cap depends on in Mexico and Central America are under severe pressure from illegal logging and climate-driven drought. The mycorrhizal tree partners I rely on are increasingly heat-stressed, causing collapses in the underground fungal networks I am part of.',
    funFact: 'Naturalist John Muir wrote about encountering indigo milk caps in California forest in the 1870s, describing them as "sapphires set in the forest floor that bled sky when you broke them."',
    emoji: '💙',
  },
];

export function getSpeciesById(id: string): Species | undefined {
  return SPECIES_DATABASE.find(s => s.id === id);
}

export function getAllSpeciesNames(): { id: string; commonName: string; scientificName: string }[] {
  return SPECIES_DATABASE.map(s => ({ id: s.id, commonName: s.commonName, scientificName: s.scientificName }));
}
